`default_nettype none

/* CRC was generated by https://bues.ch/cms/hacking/crcgen */

module axis_tx_protocol_crc 
		(
    input  wire       axis_aclk,
    input  wire       axis_reset,

    /* AXI input */
    input  wire [7:0]  s_axis_tdata,
    input  wire        s_axis_tvalid,
    output wire        s_axis_tready,
	input wire         s_axis_tlast,

    /* AXI output */
    output wire [7:0]  m_axis_tdata,
    output wire        m_axis_tvalid,
    input  wire        m_axis_tready,
    output wire        m_axis_tlast);


localparam  start_state = 2'h0,
            ready_state = 2'h1,
            tlast_state = 2'h2,
            done_state =  2'h3;

reg [15:0] curr_crc;
wire [15:0] crc_out;
reg [1:0] state;
reg [7:0] crc_data;

assign m_axis_tdata =  (state < tlast_state)?s_axis_tdata:crc_data;
assign m_axis_tvalid = (state < tlast_state)?s_axis_tvalid:m_axis_tready;
assign m_axis_tlast =  (state==done_state)?1'b1:1'b0;
assign s_axis_tready = m_axis_tready & (state == ready_state);

crc_ccitt  crc_engine(.crcIn(curr_crc),.data(s_axis_tdata),.crcOut(crc_out));

initial begin
    state = start_state;
end                

always @(posedge axis_aclk) begin

    if (!axis_reset) begin
        state <= start_state;
    end
    else begin 
        case(state)
            start_state: begin
                curr_crc <= 16'hFFFF;
                state <= ready_state;
            end

        ready_state: begin
            if (s_axis_tvalid) begin
                curr_crc <= crc_out;
                if (s_axis_tlast) begin
                    crc_data <= crc_out[15:8];
                    state <= tlast_state;
                    $display("changing states");
                end
            end
        end
        tlast_state: begin
            if ( m_axis_tready) begin
                $display("high CRC");
                crc_data <= curr_crc[7:0];
                state <= done_state; 
            end

        end
        done_state: begin
            if ( m_axis_tready) begin
                state <= start_state; 
                 $display("LOW CRC");
            end
        end

        endcase
  end
end
endmodule
/* eof */

       