# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/tcmichals/Working/xilinx/CMODS7-25/github/CMODS7/axi_dma_stream_microblaze/vivado/axis_dma/axis_dma.srcs/sources_1/bd/axis_dma_design/ip/axis_dma_design_axi_timer_0_0/axis_dma_design_axi_timer_0_0.xci
# IP: The module: 'axis_dma_design_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/tcmichals/Working/xilinx/CMODS7-25/github/CMODS7/axi_dma_stream_microblaze/vivado/axis_dma/axis_dma.srcs/sources_1/bd/axis_dma_design/ip/axis_dma_design_axi_timer_0_0/axis_dma_design_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_dma_design_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /media/tcmichals/Working/xilinx/CMODS7-25/github/CMODS7/axi_dma_stream_microblaze/vivado/axis_dma/axis_dma.srcs/sources_1/bd/axis_dma_design/ip/axis_dma_design_axi_timer_0_0/axis_dma_design_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_dma_design_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /media/tcmichals/Working/xilinx/CMODS7-25/github/CMODS7/axi_dma_stream_microblaze/vivado/axis_dma/axis_dma.srcs/sources_1/bd/axis_dma_design/ip/axis_dma_design_axi_timer_0_0/axis_dma_design_axi_timer_0_0.xci
# IP: The module: 'axis_dma_design_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/tcmichals/Working/xilinx/CMODS7-25/github/CMODS7/axi_dma_stream_microblaze/vivado/axis_dma/axis_dma.srcs/sources_1/bd/axis_dma_design/ip/axis_dma_design_axi_timer_0_0/axis_dma_design_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_dma_design_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /media/tcmichals/Working/xilinx/CMODS7-25/github/CMODS7/axi_dma_stream_microblaze/vivado/axis_dma/axis_dma.srcs/sources_1/bd/axis_dma_design/ip/axis_dma_design_axi_timer_0_0/axis_dma_design_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_dma_design_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
