# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/tcmichals/Working/xilinx/CMODS7-25/github/CMODS7/hacksterio_axi_stream_microblaze/vivado/axis_dma_microblaze/axis_dma_microblaze.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'design_1_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/tcmichals/Working/xilinx/CMODS7-25/github/CMODS7/hacksterio_axi_stream_microblaze/vivado/axis_dma_microblaze/axis_dma_microblaze.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /media/tcmichals/Working/xilinx/CMODS7-25/github/CMODS7/hacksterio_axi_stream_microblaze/vivado/axis_dma_microblaze/axis_dma_microblaze.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'design_1_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/tcmichals/Working/xilinx/CMODS7-25/github/CMODS7/hacksterio_axi_stream_microblaze/vivado/axis_dma_microblaze/axis_dma_microblaze.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
