# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CMODS7-25/Cmod-S7-25-Master.xdc

# Block Designs: bd/axis_dma_96mhz/axis_dma_96mhz.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz || ORIG_REF_NAME==axis_dma_96mhz} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_clk_wiz_0_0/axis_dma_96mhz_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_clk_wiz_0_0 || ORIG_REF_NAME==axis_dma_96mhz_clk_wiz_0_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_microblaze_0_0/axis_dma_96mhz_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_microblaze_0_0 || ORIG_REF_NAME==axis_dma_96mhz_microblaze_0_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_dlmb_v10_0/axis_dma_96mhz_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_dlmb_v10_0 || ORIG_REF_NAME==axis_dma_96mhz_dlmb_v10_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_ilmb_v10_0/axis_dma_96mhz_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_ilmb_v10_0 || ORIG_REF_NAME==axis_dma_96mhz_ilmb_v10_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_dlmb_bram_if_cntlr_0/axis_dma_96mhz_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==axis_dma_96mhz_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_ilmb_bram_if_cntlr_0/axis_dma_96mhz_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==axis_dma_96mhz_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_lmb_bram_0/axis_dma_96mhz_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_lmb_bram_0 || ORIG_REF_NAME==axis_dma_96mhz_lmb_bram_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_xbar_0/axis_dma_96mhz_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_xbar_0 || ORIG_REF_NAME==axis_dma_96mhz_xbar_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_microblaze_0_axi_periph_0/axis_dma_96mhz_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_microblaze_0_axi_periph_0 || ORIG_REF_NAME==axis_dma_96mhz_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_microblaze_0_axi_intc_0/axis_dma_96mhz_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_microblaze_0_axi_intc_0 || ORIG_REF_NAME==axis_dma_96mhz_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_microblaze_0_xlconcat_0/axis_dma_96mhz_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_microblaze_0_xlconcat_0 || ORIG_REF_NAME==axis_dma_96mhz_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_mdm_1_0/axis_dma_96mhz_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_mdm_1_0 || ORIG_REF_NAME==axis_dma_96mhz_mdm_1_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_rst_clk_wiz_0_96M_0/axis_dma_96mhz_rst_clk_wiz_0_96M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_rst_clk_wiz_0_96M_0 || ORIG_REF_NAME==axis_dma_96mhz_rst_clk_wiz_0_96M_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_axi_gpio_0_0/axis_dma_96mhz_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_axi_gpio_0_0 || ORIG_REF_NAME==axis_dma_96mhz_axi_gpio_0_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_axi_uartlite_0_0/axis_dma_96mhz_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_axi_uartlite_0_0 || ORIG_REF_NAME==axis_dma_96mhz_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_axi_timer_0_0/axis_dma_96mhz_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_axi_timer_0_0 || ORIG_REF_NAME==axis_dma_96mhz_axi_timer_0_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_uart_axis_0_0/axis_dma_96mhz_uart_axis_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_uart_axis_0_0 || ORIG_REF_NAME==axis_dma_96mhz_uart_axis_0_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_axi_dma_0_1/axis_dma_96mhz_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_axi_dma_0_1 || ORIG_REF_NAME==axis_dma_96mhz_axi_dma_0_1} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_axi_bram_ctrl_0_0/axis_dma_96mhz_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_axi_bram_ctrl_0_0 || ORIG_REF_NAME==axis_dma_96mhz_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_axi_bram_ctrl_0_bram_0/axis_dma_96mhz_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==axis_dma_96mhz_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_axis_data_fifo_0_0/axis_dma_96mhz_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_axis_data_fifo_0_0 || ORIG_REF_NAME==axis_dma_96mhz_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_axi_timer_1_0/axis_dma_96mhz_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_axi_timer_1_0 || ORIG_REF_NAME==axis_dma_96mhz_axi_timer_1_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_axi_timer_2_0/axis_dma_96mhz_axi_timer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_axi_timer_2_0 || ORIG_REF_NAME==axis_dma_96mhz_axi_timer_2_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_output_1_0_0/axis_dma_96mhz_output_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_output_1_0_0 || ORIG_REF_NAME==axis_dma_96mhz_output_1_0_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_output_1_0_1/axis_dma_96mhz_output_1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_output_1_0_1 || ORIG_REF_NAME==axis_dma_96mhz_output_1_0_1} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_output_4_0_0/axis_dma_96mhz_output_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_output_4_0_0 || ORIG_REF_NAME==axis_dma_96mhz_output_4_0_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_auto_pc_7/axis_dma_96mhz_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_auto_pc_7 || ORIG_REF_NAME==axis_dma_96mhz_auto_pc_7} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_auto_pc_0/axis_dma_96mhz_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_auto_pc_0 || ORIG_REF_NAME==axis_dma_96mhz_auto_pc_0} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_auto_pc_1/axis_dma_96mhz_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_auto_pc_1 || ORIG_REF_NAME==axis_dma_96mhz_auto_pc_1} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_auto_pc_2/axis_dma_96mhz_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_auto_pc_2 || ORIG_REF_NAME==axis_dma_96mhz_auto_pc_2} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_auto_pc_3/axis_dma_96mhz_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_auto_pc_3 || ORIG_REF_NAME==axis_dma_96mhz_auto_pc_3} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_auto_pc_4/axis_dma_96mhz_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_auto_pc_4 || ORIG_REF_NAME==axis_dma_96mhz_auto_pc_4} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_auto_pc_5/axis_dma_96mhz_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_auto_pc_5 || ORIG_REF_NAME==axis_dma_96mhz_auto_pc_5} -quiet] -quiet

# IP: bd/axis_dma_96mhz/ip/axis_dma_96mhz_auto_pc_6/axis_dma_96mhz_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dma_96mhz_auto_pc_6 || ORIG_REF_NAME==axis_dma_96mhz_auto_pc_6} -quiet] -quiet

# XDC: bd/axis_dma_96mhz/axis_dma_96mhz_ooc.xdc
